### ISSUE TITLE
You really need better examples for datasource

### ISSUE THREAD

**Issue by Stefdv** [bluewatertracks/bwt-datatable#10]
I think you should provide examples on how to use datasource inside a custom element.
Right now the only examples are using `template is=bind`  , i'm having a hard time finding out how to setup a datasource inside a custom app.
Also it is not clear when certain functions are called (queryForIds,getByIds,get,set)

**Comment by maisnamraju** [comment]
We are working on improving the documentation so will have a look at this. as well as the bug

**Comment by Stefdv** [comment]
👍

**Comment by samiheikki** [comment]
+1. Was trying to implement something similar to this: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/data.html#assigning-remote-function-data Any pointers where to start?

**Comment by dhrytsenko** [comment]
Hi @samiheikki! If you want to use simple datatable you can check this example [simple datatable](https://github.com/bluewatertracks/bwt-datatable/blob/master/demo/paper-datatable/index.html)

**Comment by samiheikki** [comment]
Actually found this https://github.com/bluewatertracks/bwt-datatable/blob/master/demo/paper-datatable-card/index.html#L69 and that helped me a lot. Thanks!

**Comment by dhrytsenko** [comment]
@samiheikki You're welcome!
