### ISSUE TITLE
Support for polymer 2.0

### ISSUE THREAD

**Issue by ghost** [bluewatertracks/bwt-datatable#15]
First of all thanks for working on this great library. Second, is there any play to migrate base code from polymer 1 to polymer 2. I have read polymer 2 specs and it was great but this important library i use seems to doesn't support it. (i have tested it and it doesn't work)

**Comment by dhrytsenko** [comment]
Hi @aryaei. Thank you. 

We have plans to do it. I worked on [hybrid mode](https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements) for compatibility with both Polymer 1 and 2 versions and there were few bugs with it. I'II wait until Polymer 2 will be stable and then complete a work on datatable.

**Comment by ghost** [comment]
thanks a lot

**Comment by ArthurJahn** [comment]
Any updates here?

**Comment by dhrytsenko** [comment]
@ArthurJahn It works with Polymer 2 in hybrid mode. Work still in progress cause we should change a lot of code

**Comment by ArthurJahn** [comment]
ok! thanks
