### ISSUE TITLE
The pagination info and buttons at the bottom of paper-datatable-card should update when searching

### ISSUE THREAD

**Issue by benmiller86** [bluewatertracks/bwt-datatable#20]
As it stands when you search and filter you data the pagination info (x-y of z) at the bottom of the paper-datatable-card element do not update as you filter the data. Additionally the pagination buttons do not update their state, so you are free to navigate to empty pages after you have filtered your data.

This is of course assuming that I haven't just missed the functionality that would allow me to update things in the docs, if so apologies in advance! :-)

**Comment by dhrytsenko** [comment]
@benmiller86 Thank you. l will work on it

**Comment by dhrytsenko** [comment]
Closed due to inactivity. You can open it again if still have this problem
