### ISSUE TITLE
Using multiple properties in one column

### ISSUE THREAD

**Issue by chavu** [bluewatertracks/bwt-datatable#24]
How do I use multiple properties in one column. I want to put a URL link which should be made of values from multiple properties as below:

<datatable-column header "Supplier" property="supplier"> </datatable-column > 
<datatable-column header "Product" property="product"> </datatable-column > 
<datatable-column header "Buy Link"> 
   <template> 
     <a href="/path/{{value-in-provider-property}}>/{{value-in-product-property}}"> Buy </a>
   <template>
</datatable-column>

**Comment by dhrytsenko** [comment]
You can use it with `<template>` tag like this:

    <datatable-column header "Buy Link">
         <template is="dom bind"><a href$="[[item.supplier]]/[[item.product]]">Buy Link</a></template>
    </datatable-column>

Or you can add on-tap event listener to column or table and do the same but with JS:

    <paper-datatable on-row-tap="_goToSupplier"></paper-datatable>

JS code

    _goToSupplier: function(e) {
	var product = e.detail.item.product;
	var supplier = e.detail.item.supplier;
        var url = supplier + "/" + product;
	window.open(url, '_blank');
}

**Comment by dhrytsenko** [comment]
Closed for inactivity
