### ISSUE TITLE
Confusing Names In Demo Example

### ISSUE THREAD

**Issue by Thkasis** [bluewatertracks/bwt-datatable#27]
Hi, Great work! I was just checking the examples given in demo section of the guid and I noticed they are not using bwt-datatable-card and instead are using paper-datatable-card , etc ... It would be helpful to change the elements to use bwt... Also noticed; when trying to use datatable-paper ; weakCache.js is loaded twice; judging by netweork in chrome dev tools. Cheers

**Comment by dhrytsenko** [comment]
Hi @Thkasis. We leave name like `paper-datatable-card` for backward compatibility with David Malder's `paper-datatable` cause many people still use it and it can be little painful to change names everywhere to `bwt-datatable` etc. 
Good point about `weakCache.js`. l will check it. Thank you

**Comment by dhrytsenko** [comment]
Fixed in new version 1.0.12
