### ISSUE TITLE
Range start should not be zero-based

### ISSUE THREAD

**Issue by marcelojgarcia** [bluewatertracks/bwt-datatable#33]
In all examples provided, the range start of the page is zero-base, i.e. if there are 10 rows per page, data-table footer shows "Rows per page: 10 / <strong>0</strong>-10 of N"
It should show "Rows per page: 10 / <strong>1</strong>-10 of N"

**Comment by dhrytsenko** [comment]
Thanks, @marcelojgarcia. I will check

**Comment by dhrytsenko** [comment]
Fixed in PR #34
