### ISSUE TITLE
DOMException on simple app

### ISSUE THREAD

**Issue by marcelojgarcia** [bluewatertracks/bwt-datatable#35]
I'm getting "**DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node**" after adding the datatable to a simple app.
Steps to reproduce:
polymer init (choose  polymer-2-starter-kit option)
bower install --save bluewatertracks/bwt-datatable
vi src/my-view1.html
add import for paper-datatable.html
add component just after card div
After polymer serve command check the app on browser.

**Comment by dhrytsenko** [comment]
I'll check, thanks

**Comment by marcelojgarcia** [comment]
Hi dhrytsenko,
   Still don't know what was causing the problem, but today after uninstall/reinstall polymer-cli and bower, and cleaning up the caches, it's working perfectly.
  No need to further investigation.
Thanks a lot for the support.

**Comment by dhrytsenko** [comment]
Ok, good to hear that. I'll close this issue then
