### ISSUE TITLE
Uncaught ReferenceError: CollectionHelpers is not defined

### ISSUE THREAD

**Issue by chavu** [bluewatertracks/bwt-datatable#38]
I'm getting the error message below and non of my bwt-tables are working. They were working before.

---
Uncaught ReferenceError: CollectionHelpers is not defined
---
![image](https://user-images.githubusercontent.com/12425046/34570914-d7a2b2c8-f175-11e7-9f33-7eff7fffc286.png)

**Comment by bhargavkonkathi** [comment]
Hello @chavu ,

We have updated bwt-datatable, with adding support for Polymer 2.x Version , If your using in polymer version 2 Please reinstall bwt-datatable with all its dependencies, Hope that resolves your problem. Also Will your share gist snippet of bwt-datatable how your using in your project, to resolve problem easily. And which version of bwt-datatable your using?

Thanks,

**Comment by chavu** [comment]
Yes I'm using Polymer 2, in [Cuba Framework 6.7](cuba-platform.com)
I add the latest version of bwt-datatable ver 2.0.4 by entering the following line in bower.json file.
"bwt-datatable": "bluewatertracks/bwt-datatable#^2.0.4",

Attached is  one of the views I'm using bwt-datable. Somehow the browser is not loading the contents of  the .js files: collectionHelpers.js and weakCache.js but they are there in the src folder.

[betwise-odd-highlights.txt](https://github.com/bluewatertracks/bwt-datatable/files/1607332/betwise-odd-highlights.txt)

**Comment by GermanMtzmx** [comment]
@bhargavkonkathi i have the same error, doing a polymer build 'es6-unbundled' the content of CollectionHelpers & and weakCahe disappears

**Comment by dhrytsenko** [comment]
@GermanMtzmx @chavu I know what a problem. I'm going to update `bwt-datatable` in one hour

**Comment by dhrytsenko** [comment]
Fixed in new 2.1.0 release

**Comment by chavu** [comment]
Thank you @dhrytsenko
