### ISSUE TITLE
publish on npm

### ISSUE THREAD

**Issue by abdulhannanali** [bluewatertracks/bwt-datatable#41]
Seriously please consider publishing custom elements on npm/yarn too to give public more choice for the package managers supported. Many people are done with bower, so it's going to be a big community service on your behalf. Bower is also not recommended by the maintainers themselves. Here's a statement as y'all might know from their homepage. 
 
[![image](https://user-images.githubusercontent.com/8170969/35737805-9c8732be-084e-11e8-8333-11b0ce1988b6.png)](https://bower.io)

**Comment by dhrytsenko** [comment]
@abdulhannanali Thank you for your notes. I'll do it on this week

**Comment by dhrytsenko** [comment]
@abdulhannanali This element was published on npm. Check out https://www.npmjs.com/package/bwt-datatable

**Comment by abdulhannanali** [comment]
Thanks @dhrytsenko
