### ISSUE TITLE
Dynamically set editable

### ISSUE THREAD

**Issue by mlabarre** [bluewatertracks/bwt-datatable#43]
Hello
It would have been interesting to type the property editable in string and not in boolean. This would have allowed to code editable = "false | true". Because only the presence of the editable attribute puts the field editable! So editable="[[_isEditable]] does not works (Polymer design).

**Comment by dhrytsenko** [comment]
@mlabarre I think editable property should have `Booelan` type. Please open this issue again if you have more questions
