### ISSUE TITLE
sub tables

### ISSUE THREAD

**Issue by rom1504** [bluewatertracks/bwt-datatable#45]
Is it be possible to do something like https://datatables.net/examples/api/row_details.html using bwt-datatable ?

**Comment by dhrytsenko** [comment]
@rom1504 Right now no. You can only get row details when edit it.

**Comment by rom1504** [comment]
Ok so why did you close the issue ?
This is an important feature to have to be able to use this lib instead of jQuery datatable.

**Comment by dhrytsenko** [comment]
@rom1504 I can leave it open. I thought it was a question and not a request for enhancement. I don't have plans to do it in the near future cause we are going to work on code rewriting for Polymer 3

**Comment by azatprog** [comment]
@dhrytsenko could you tell when it could be done rewriting for Polymer 3?

**Comment by dmytrohrytsenko** [comment]
@azatprog We don't have plans to rewrite it right now but we will do it in a near future.

**Comment by dhrytsenko** [comment]
@azatprog It should be ready today with a new stable release and new demos!
