### ISSUE TITLE
bwt-datatable as vanilla webcomponent

### ISSUE THREAD

**Issue by R300655** [bluewatertracks/bwt-datatable#47]
Would it be a considerable expenditure to convert the existing polymer version of bwt-datatable to a vanilla webcomponent for example with Ionic's Stencil?

**Comment by dhrytsenko** [comment]
Sorry for late response @Rolf2012 but I didn't work with Ionic's Stencil but this table is using Polymer's code as much as it can so it could be not easy to rewrite it to vanilla webcomponent. I'm planning to update it to and support Polymer 3 and new es6 syntax. Please open this issue if you have more questions
