### ISSUE TITLE
please update iron-flex-layout

### ISSUE THREAD

**Issue by Stefdv** [bluewatertracks/bwt-datatable#6]
`iron-shadow-flex-layout` is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead.
This file is deprecated. Please use `iron-flex-layout/iron-flex-layout-classes.html`, and one of the specific dom-modules instead.

BTW  tx for developing this further

**Comment by dhrytsenko** [comment]
Hi @Stefdv ! Thank you for your attention. I'II fix it

**Comment by dhrytsenko** [comment]
Hi @Stefdv! I fix this issue, please check it out and close this issue.

**Comment by Stefdv** [comment]
Sorry..for my late reaction.
Tx 👍
