### ISSUE TITLE
Is there any way to fix headers positions

### ISSUE THREAD

**Issue by mukuls-brdsys** [bluewatertracks/bwt-datatable#8]
Can the headers be prevented from scrolling with the content? So the user can see what the column refers to while scrolling.

**Comment by dhrytsenko** [comment]
Hi @mukuls-brdsys! Do you mean headers for each columns? Can you describe the situation in which we need this stuff? I think you ask about `resize-behavior` prop equal to `overflow`

**Comment by mukuls-brdsys** [comment]
Yes, headers for each column. This could be useful when there are many rows without pagination. So if the user scrolls down sometimes it is not clear what the column represents. I, for example, was using the component to display user preferences which contain checkboxes. So when the user scrolls down it is not clear which column represent which preference.

**Comment by dhrytsenko** [comment]
Hi @mukuls-brdsys! I think it makes sense. I'll try to find a way to add this feature

**Comment by dhrytsenko** [comment]
Hi @mukuls-brdsys! I just update a version of datatable with new changes. You can fix a table header to the top now. Check [this](https://bluewatertracks.github.io/bwt-datatable/components/bwt-datatable/docs/docs.html?getting-started#fixed-header) and example in readme

**Comment by mukuls-brdsys** [comment]
Thanks. Appreciate it.
